### ISSUE TITLE
Not open in pane and the response tab doesn't get the focus

### ISSUE THREAD

**Issue by Azakur4** [pjdietz/rester-atom#18]
I want to know that is possible get an option to not open in a split mode (pane)

**Comment by pjdietz** [comment]
I merged your PR. Look for these changes in v1.1.0+. Thanks!

**Comment by Azakur4** [comment]
Oh thanks men, u will publish that version? i try to reinstall ur package but still come version 1.0.2

**Comment by pjdietz** [comment]
v1.1.1 should be published now.

**Comment by Azakur4** [comment]
Yeah! thanks men.
