### ISSUE TITLE
UTF-8 special chars causes wrong content-length calculation

### ISSUE THREAD

**Issue by dbiagi** [pjdietz/rester-atom#20]
When sending utf8 special chars on request body, the Content-Length is calculated incorrectly resulting in content truncation.

FYI I'm using https://requestb.in to test the requests.

Fail case:
```
POST https://requestb.in/xmh7sfxm

{
    "test": "aá"
}
```
![image](https://user-images.githubusercontent.com/6682510/28348262-624fc6ca-6c12-11e7-8974-1af5b0dcb07e.png)

The response body is truncated because content length is 20, when the correctly value should be 21.

When setting the length at the request kinda solve the problem.

```
POST https://requestb.in/xmh7sfxm
Content-Length: 21

{
    "test": "aá"
}
```

![image](https://user-images.githubusercontent.com/6682510/28348381-23f60316-6c13-11e7-8c41-dd22abf7a9a5.png)

I really think this should be handled by the package internally.

The closest related problem I found on the internet was this issue https://github.com/expressjs/express/issues/1816

I think I can provide a PR to this. I'll take a look at the code.

**Comment by pjdietz** [comment]
Thanks, I made an update to the underlying library to calculate the content-length as UTF-8. This should fix things for your use case and work correctly for most. This is a safe default, but I should probably add something in to check against the `content-type` header.
